name: Checked delivery
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          packages: |
            github::dataraft-r/dataraft.core
            github::dataraft-r/dataraft.adapters
      - run: Rscript run.R
